### ISSUE TITLE
How do you filter results?

### ISSUE THREAD

**Issue by michael-lawrence** [shlomiassaf/resty-stone#20]
I couldn't seem to find an example of how to filter results. How is this accomplished?
Assume that I'm getting a collection of Posts with a createdDate property. How would I grab only the posts within a range of dates?

If you can't do ranges, can you do simple matches? For example:
/api/posts?title=Post%201

That doesn't work, but how exactly should the url look?

Thanks!

**Comment by michael-lawrence** [comment]
Nevermind. I believe I found it. Here is how I'm doing it for anyone else that may wonder how it's done:

``` javascript
restList._render = function (req, instance) {
    if (req.query.title) {
        return (instance.title === req.query.title) ? instance : null;
    }

    return instance;
};

module.exports.default = {
    'httpMethods': 'get',
    'httpGroupMethods': 'get',
    'defaultKey': 'name',
    'permanentFilter': 'isActive',
    'columns': {
        'visible': [
            'title'
        ]
    },
    'RestList': restList
};
```

**Comment by shlomiassaf** [comment]
There are better ways to achieve what you want...

When you filter via "render" you actually do a bigger query then spend work on reducing it...

resty-stone uses the built-in filtering system used by keystone.
It is achieved via "q" parameter or "search" parameter.
q is the built-in keystone made filtering system.
search is the mongoose system.

They both work, you should read about it in the keystone docs/google groups.

I tried to stick with keystone core whenever possible.
a - it saves time.
b - it keeps consistency.

**Comment by michael-lawrence** [comment]
That's awesome! Is there documentation anywhere on using the "q" query string parameter? I searched keystone's documentation as well as resty-stone's and didn't see it mentioned anywhere.

**Comment by shlomiassaf** [comment]
This is quite an issue as there is no clear documentation for it in KeystoneJS.

Basically it is a separate NPM package called [queryfilter](https://www.npmjs.com/package/queryfilter) ([GitHub](https://github.com/keystonejs/queryfilter))

Here is a little example you can play with to get a better understanding.
- Create a directory 
- Install the package: `npm install queryfilter`
- Create a file and paste the following code:

```
var qf = require("queryfilter");

var queryExamples = [
    'title:hello',
    'title:=:hello',
    'title:!:hello',
    'title:hello:world',
    'quantity:lt:15',
    'quantity:gt:15',
    'quantity:bt:15:20',
    'title:hello;quantity:lt:15'
];

queryExamples.forEach(function(query){
    console.log(
        query + ' ==> ' + qf.QueryFilters.create(query).toHumanString()
    );
});
```

You should get the following results:

```
title:hello ==> title matches hello
title:=:hello ==> title exactly matches hello
title:!:hello ==> title does not match hello
title:hello:world ==> title matches hello and world
quantity:lt:15 ==> quantity matches less than 15
quantity:gt:15 ==> quantity matches greater than 15
quantity:bt:15:20 ==> quantity matches between 15 and 20
title:hello;quantity:lt:15 ==> title matches hello and quantity matches less than 15
```

The same idea apply with query string, you just post it as a `q` parameter:
`http:\\www.example.com\api\posts?q=title:hello`

**Comment by michael-lawrence** [comment]
Thanks! That gets me started. I really wish they provided documentation on all of the possible options. :+1:
